### ISSUE TITLE
Allow 830 as time

### ISSUE THREAD

**Issue by eigan** [LeanderGangso/goc#10]
```
goc s -t 830 "My task"             
utils.go:95: unable to parse time: parsing time "2022-11-15 830 CET": hour out of range
```

Zeropad the -t value when the value is three digets might solve this? What do you think?

**Comment by LeanderGangso** [comment]
Implemented in latest commit: [8fa7cc0](https://github.com/LeanderGangso/goc/commit/8fa7cc0e9e4871ca986f34d73c2ecec53949eaaf)
