### ISSUE TITLE
[Feature request] Possible to see total duration of all tasks today

### ISSUE THREAD

**Issue by eigan** [LeanderGangso/goc#8]
Not sure how we can solve this, but here is an idea:

- Expect that `goc` is the only tracker you use for inserting tasks.
- When insert new task in Gcal, also fetch all other entries today.
  - Calculate the total duration on all of these entries
  - Store that time in data.json.
- We can now calculate the total time by doing `cachedCurrentTotalDuration + durationOfCurrentTask`

**Comment by LeanderGangso** [comment]
feature implemented
